# Configuration for pygrid.
qstat-timeout-seconds = 60
qsub-timeout-seconds = 60
qconf-timeout-seconds = 60
qdel-timeout-seconds = 60
on-failure-timeout-seconds = 300
qstat-long-job-names = 200
real-failure-messages = [
    "invalid",
    "rejected",
    "unknown command from JSV",
]
# From sge_job.h in gridengine source code
# Numbers on the right correspond to the bit-masks
# qstat uses to report current status of each task.
job-states = '''
#define JIDLE                                0x00000000
#define JHELD                                0x00000010
#define JMIGRATING                           0x00000020
#define JQUEUED                              0x00000040
#define JRUNNING                             0x00000080
#define JSUSPENDED                           0x00000100
#define JTRANSFERING                         0x00000200
#define JDELETED                             0x00000400
#define JWAITING                             0x00000800
#define JEXITING                             0x00001000
#define JWRITTEN                             0x00002000
#define JWAITING4OSJID                       0x00004000
#define JERROR 0x00008000
'''
restart-file-location = "/ihme/temp/sgeoutput/{user}/restart"
queues = ["all.q", "long.q"]
project = "ihme_general"
qsub-shell-file-directory = "/ihme/code/{user}/shellfiles"
cluster-tmp = "/ihme/temp/sgeoutput/{user}"
